version: '3.3'

services:
  postgres:
    container_name: alpa-postgres
    hostname: alpa-postgres
    build: ./postgres
    ports:
       - "5432:5432"
    command: postgres -c max_connections=200
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=postgres

  pgadmin:
    container_name: alpa-pgadmin
    hostname: alpa-pgadmin
    build: ./pgadmin
    ports:
      - "9090:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@localhost
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - postgres