server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://backend-postgres:5433/issue_tracker
    username: usr
    password: pwd
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8484/realms/issue_tracker/protocol/openid-connect/certs

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE