server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/issue_tracker
    username: usr
    password: pwd

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE